
development:
  stripe_secret_key: 'sk_test_sTPsmGzcy9jA6i74jcFRJOd700sBkkKidc'
  stripe_publishable_key: 'pk_test_lRvozy2evAGW3hLzbhpht3Dy00SSr8YXjC'

production:
  stripe_secret_key: 'sk_test_sTPsmGzcy9jA6i74jcFRJOd700sBkkKidc'
  stripe_publishable_key: 'pk_test_lRvozy2evAGW3hLzbhpht3Dy00SSr8YXjC'